name: Profile Readme Development Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with WakaTime stats
        uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          SHOW_OS: "False"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_COMMIT: "False"
          SHOW_LANGUAGE: "True"
          SHOW_LINES_OF_CODE: "False"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LOC_CHART: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_UPDATED_DATE: "False"
          SHOW_TOTAL_CODE_TIME: "True"
