name: Wakatime Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  update-readme-with-wakatime-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Wakatime stats
        uses: claserre9/wakatime-stats@v1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_USER_ID: ${{ secrets.WAKATIME_USER_ID }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
